attrs:
  title: Sofar Spotter Buoy
  description:
    Example ingest of raw XYZ and GPS data taken by a Sofar Spotter buoy deployed in
    Clallam Bay, WA
  location_id: clallam
  dataset_name: spotter
  data_level: a1
  qualifier: gps
  temporal: 1min
  institution: Pacific Northwest National Laboratory

coords:
  time:
    dims: [time]
    dtype: datetime64[ms]
    attrs:
      units: Seconds since 1970-01-01 00:00:00
      long_name: Time
      standard_name: time
      timezone: UTC

data_vars:
  lat:
    dims: [time]
    dtype: float32
    attrs:
      units: deg_N
      long_name: Latitude
      standard_name: latitude
      valid_min: -90
      valid_max: 90
  lon:
    dims: [time]
    dtype: float32
    attrs:
      units: deg_E
      long_name: Longitude
      standard_name: longitude
      valid_min: -180
      valid_max: 180
