classname: pipelines.waves.pipeline.Waves

triggers:
  - .*LOC.CSV

retriever:
  path: pipelines/waves/config/retriever.yaml

dataset:
  path: pipelines/waves/config/dataset_loc.yaml

quality:
  path: pipelines/waves/config/quality.yaml
storage:
  path: shared/storage.yaml
