classname: tsdat.io.retrievers.DefaultRetriever
readers:
  .*FLT.*:
    classname: tsdat.io.readers.CSVReader
    parameters:
      read_csv_kwargs:
        delimiter: ","
        index_col: false
  .*LOC.*:
    classname: pipelines.waves.readers.GPSReader

coords:
  time:
    .*:
      name: [time, GPS_Epoch_Time(s)]

data_vars:
  surge:
    .*FLT.*:
      name: outx(mm)
      data_converters:
        - classname: tsdat.io.converters.UnitsConverter
          input_units: mm
  sway:
    .*FLT.*:
      name: outy(mm)
      data_converters:
        - classname: tsdat.io.converters.UnitsConverter
          input_units: mm
  heave:
    .*FLT.*:
      name: outz(mm)
      data_converters:
        - classname: tsdat.io.converters.UnitsConverter
          input_units: mm

  lat:
    .*LOC.*:
      name: lat

  lon:
    .*LOC.*:
      name: lon
