classname: pipelines.vap_buoy_motion.pipeline.VapWaves
parameters:
  datastreams:
    - clallam.spotter-pos-400ms.a1
    - clallam.spotter-gps-1min.a1

triggers: []

retriever:
  path: pipelines/vap_buoy_motion/config/retriever.yaml

dataset:
  path: pipelines/vap_buoy_motion/config/dataset.yaml

quality:
  path: pipelines/vap_buoy_motion/config/quality.yaml
storage:
  path: shared/storage.yaml
