classname: tsdat.io.retrievers.StorageRetriever
parameters:
  transformation_parameters:
    # Where the point lies in the coordinate bounds (CENTER, LEFT, RIGHT)
    alignment:
      time: CENTER

    # How far to look for the next available data point
    range:
      time: 60

    # Width of the transformation
    width:
      time: 60

coords:
  time:
    .*pos.*:
      name: time
    # name: N/A
    # data_converters:
    #   - classname: tsdat.transform.CreateTimeGrid
    #     interval: 400ms
  frequency:
    .*pos.*: 
      name: frequency

data_vars:
  x:
    .*pos.*:
      name: x
  y:
    .*pos.*:
      name: y
  z:
    .*pos.*:
      name: z

  lat:
    .*gps.*:
      name: lat
      data_converters:
        - classname: tsdat.transform.NearestNeighbor
  lon:
    .*gps.*:
      name: lon
      data_converters:
        - classname: tsdat.transform.NearestNeighbor
