attrs:
  title: Clallam Bay Wave Data
  description:
    Sea surface temperature taken by a Sofar Spotter buoy deployed in Clallam Bay, WA
  location_id: clallam
  dataset_name: spotter
  data_level: a1
  qualifier: sst
  temporal: 1min
  institution: Pacific Northwest National Laboratory

coords:
  time:
    dims: [time]
    dtype: datetime64[ms]
    attrs:
      units: Seconds since 1970-01-01 00:00:00 UTC
      long_name: Time
      standard_name: time
      timezone: UTC

data_vars:
  sst:
    dims: [time]
    dtype: float32
    attrs:
      units: degC
      long_name: Sea Surface Temperature
      standard_name: sea_surface_temperature
      valid_min: 0
      valid_max: 40
