attrs:
  title: Clallam Bay GPS Data
  description:
    GPS data measured by a Sofar Spotter wave buoy deployed in Clallam Bay, WA
  location_id: clallam
  dataset_name: spotter
  data_level: a1
  qualifier: gps
  temporal: 1min
  institution: Pacific Northwest National Laboratory

coords:
  time:
    dims: [time]
    dtype: datetime64[ms]
    attrs:
      units: Seconds since 1970-01-01 00:00:00 UTC
      long_name: Time
      standard_name: time
      timezone: UTC

data_vars:
  lat:
    dims: [time]
    dtype: float32
    attrs:
      units: degree_north
      long_name: Latitude
      standard_name: latitude
      valid_min: -90
      valid_max: 90
  lon:
    dims: [time]
    dtype: float32
    attrs:
      units: degree_east
      long_name: Longitude
      standard_name: longitude
      valid_min: -180
      valid_max: 180
