classname: pipelines.spotter.pipeline.Waves

triggers:
  - .*SST.CSV

retriever:
  path: pipelines/spotter/config/retriever.yaml

dataset:
  path: pipelines/spotter/config/dataset_sst.yaml

quality:
  path: pipelines/spotter/config/quality.yaml
storage:
  path: shared/storage.yaml
