classname: pipelines.vap_wave_stats.pipeline.VapWaveStats
parameters:
  datastreams:
    - clallam.wave.c0
    - clallam.spotter-gps-1min.a1

triggers: []

retriever:
  path: pipelines/vap_wave_stats/config/retriever.yaml

dataset:
  path: pipelines/vap_wave_stats/config/dataset.yaml

quality:
  path: shared/quality.yaml
storage:
  path: shared/storage.yaml
