classname: pipelines.spotter_v1.pipeline.Waves

triggers:
  - .*SST.CSV

retriever:
  path: pipelines/spotter_v1/config/retriever.yaml

dataset:
  path: pipelines/spotter_v1/config/dataset_sst.yaml

quality:
  path: pipelines/spotter_v1/config/quality.yaml
storage:
  path: shared/storage.yaml
