classname: pipelines.vap_combine.pipeline.VapWaveStats
parameters:
  datastreams:
    - clallam.wave.c0
    - clallam.gps.c0

triggers: []

retriever:
  path: pipelines/vap_combine/config/retriever.yaml

dataset:
  path: pipelines/vap_combine/config/dataset.yaml

quality:
  path: shared/quality.yaml
storage:
  path: shared/storage.yaml
