classname: tsdat.io.retrievers.StorageRetriever
parameters:
  fetch_parameters:
    # How far in time to look after the "end" timestamp (+), before the "begin"
    # timestamp (-), or both (none) to find filenames that contain needed data
    file_padding: 12h

  transformation_parameters:
    # Where the point lies in the coordinate bounds (CENTER, LEFT, RIGHT)
    alignment:
      time: CENTER

    # How far to look for the next available data point
    range:
      time: 60s

    # Width of the transformation
    width:
      time: 60s

coords:
  time:
    .*gps.*:
      name: time
  frequency:
    .*wave.*: 
      name: frequency

data_vars:
  lat:
    .*gps.*:
      name: lat
  lon:
    .*gps.*:
      name: lon

  wave_hs:
    .*wave.*: 
      name: wave_hs
      data_converters:
        - classname: tsdat.transform.NearestNeighbor
          coord: time
  wave_te:
    .*wave.*: 
      name: wave_te
      data_converters:
        - classname: tsdat.transform.NearestNeighbor
          coord: time
  wave_tp:
    .*wave.*: 
      name: wave_tp
      data_converters:
        - classname: tsdat.transform.NearestNeighbor
          coord: time
  wave_ta:
    .*wave.*: 
      name: wave_ta
      data_converters:
        - classname: tsdat.transform.NearestNeighbor
          coord: time
  wave_tz:
    .*wave.*: 
      name: wave_tz
      data_converters:
        - classname: tsdat.transform.NearestNeighbor
          coord: time
  wave_dp:
    .*wave.*: 
      name: wave_dp
      data_converters:
        - classname: tsdat.transform.NearestNeighbor
          coord: time
  wave_spread:
    .*wave.*: 
      name: wave_spread
      data_converters:
        - classname: tsdat.transform.NearestNeighbor
          coord: time
  wave_energy_density:
    .*wave.*: 
      name: wave_energy_density
      data_converters:
        - classname: tsdat.transform.NearestNeighbor
          coord: time
  wave_a1_value:
    .*wave.*: 
      name: wave_a1_value
      data_converters:
        - classname: tsdat.transform.NearestNeighbor
          coord: time
  wave_b1_value:
    .*wave.*: 
      name: wave_b1_value
      data_converters:
        - classname: tsdat.transform.NearestNeighbor
          coord: time
  wave_a2_value:
    .*wave.*: 
      name: wave_a2_value
      data_converters:
        - classname: tsdat.transform.NearestNeighbor
          coord: time
  wave_b2_value:
    .*wave.*: 
      name: wave_b2_value
      data_converters:
        - classname: tsdat.transform.NearestNeighbor
          coord: time
  wave_check_factor:
    .*wave.*: 
      name: wave_check_factor
      data_converters:
        - classname: tsdat.transform.NearestNeighbor
          coord: time
