classname: pipelines.vap_wave_v2.pipeline.VapWaveStats
parameters:
  datastreams:
    - pnnl.spotter-32632C.a1

triggers: []

retriever:
  path: pipelines/vap_wave_v2/config/retriever.yaml

dataset:
  path: pipelines/vap_wave_v2/config/dataset.yaml

quality:
  path: shared/quality.yaml
storage:
  path: shared/storage.yaml
