classname: tsdat.io.retrievers.StorageRetriever
parameters:
  fetch_parameters:
    # How far in time to look after the "end" timestamp (+), before the "begin"
    # timestamp (-), or both (none) to find filenames that contain needed data
    time_padding: -24h

  transformation_parameters:
    # Where the point lies in the coordinate bounds (CENTER, LEFT, RIGHT)
    alignment:
      time: CENTER
    # How far to look for the next available data point
    range:
      time: 1s
    # Width of the transformation
    width:
      time: 1s

coords:
  time:
    name: time
    data_converters:
      - classname: tsdat.transform.CreateTimeGrid
        interval: 400ms
  time_aux:
    name: time_aux
  frequency:
    .*:
      name: frequency
  direction:
    .*: 
      name: direction

data_vars:
  x:
    .*:
      name: x
      data_converters:
        - classname: tsdat.transform_v2.NearestNeighbor
          coord: time
  y:
    .*:
      name: y
      data_converters:
        - classname: tsdat.transform_v2.NearestNeighbor
          coord: time
  z:
    .*:
      name: z
      data_converters:
        - classname: tsdat.transform_v2.NearestNeighbor
          coord: time
  latitude:
    .*:
      name: latitude
  longitude:
    .*:
      name: longitude
  sea_surface_temperature:
    .*:
      name: sea_surface_temperature
  air_temperature:
    .*: 
      name: air_temperature
  humidity: 
    .*: 
      name: humidity
  air_pressure:
    .*:
      name: air_pressure
