classname: tsdat.io.retrievers.StorageRetriever
parameters:
  fetch_parameters:
    # How far in time to look after the "end" timestamp (+), before the "begin"
    # timestamp (-), or both (none) to find filenames that contain needed data
    time_padding: -24h

  transformation_parameters:
    # Where the point lies in the coordinate bounds (CENTER, LEFT, RIGHT)
    alignment:
      time: CENTER

    # How far to look for the next available data point
    range:
      time: 120s

    # Width of the transformation
    width:
      time: 60s

coords:
  time:
    .*:
      name: time
  frequency:
    .*: 
      name: frequency
  direction:
    .*: 
      name: direction

data_vars:
  x:
    .*:
      name: x
  y:
    .*:
      name: y
  z:
    .*:
      name: z
  latitude:
    .*:
      name: latitude
  longitude:
    .*:
      name: longitude
  sea_surface_temperature:
    .*:
      name: sea_surface_temperature
  air_temperature:
    .*: 
      name: air_temperature
  humidity: 
    .*: 
      name: humidity
  air_pressure:
    .*:
      name: air_pressure
