attrs:
  title: Wave Statistics
  description:
    Wave statistics measured by a Sofar Spotter wave buoy deployed in Clallam Bay, WA
  location_id: clallam
  dataset_name: wave
  data_level: c0

coords:
  time:
    dims: [time]
    dtype: datetime64[ms]
    attrs:
      units: Seconds since 1970-01-01 00:00:00 UTC
      long_name: Time
      standard_name: time
      timezone: UTC
      coverage_content_type: coordinate

  frequency:
    dims: [frequency]
    dtype: float32
    attrs:
      long_name: Band Center Frequency
      units: Hz
      standard_name: wave_frequency

data_vars:
  x:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Buoy Surge
      standard_name: platform_surge
      units: m
      valid_min: -8
      valid_max: 8
  y:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Buoy Sway
      standard_name: platform_sway
      units: m
      valid_min: -8
      valid_max: 8
  z:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Buoy Heave
      standard_name: platform_heave
      units: m
      valid_min: -8
      valid_max: 8

  wave_hs:
    dims: [time]
    dtype: float32
    attrs:
      long_name: significant wave height
      units: m
      standard_name: sea_surface_wave_significant_height
      valid_min: 0.0
      valid_max: 20.0
  wave_te:
    dims: [time]
    dtype: float32
    attrs:
      long_name: wave energy period
      units: s
      standard_name: sea_surface_wave_mean_period_from_variance_spectral_density_inverse_frequency_moment
      additional_processing:
        Calculated from the full-spectrum, buoy-returned energy density values.
  wave_tp:
    dims: [time]
    dtype: float32
    attrs:
      long_name: peak wave period
      units: s
      standard_name: sea_surface_wave_period_at_variance_spectral_density_maximum
      valid_min: 0.0
      valid_max: 40.0
  wave_ta:
    dims: [time]
    dtype: float32
    attrs:
      long_name: average wave period
      units: s
      standard_name: sea_surface_wave_mean_period_from_variance_spectral_density_first_frequency_moment
      valid_min: 0.0
      valid_max: 40.0
      additional_processing:
        Calculated from the full-spectrum, buoy-returned energy density values.
  wave_tz:
    dims: [time]
    dtype: float32
    attrs:
      long_name: spectral zero-upcross wave period
      units: s
      standard_name: sea_surface_wave_zero_upcrossing_period
      valid_min: 0.0
      valid_max: 40.0

  wave_dp:
    dims: [time]
    dtype: float32
    attrs:
      long_name: peak wave direction
      units: deg_true
      standard_name: sea_surface_wave_from_direction
      valid_min: 0.0
      valid_max: 360.0
  wave_spread:
    dims: [time]
    dtype: float32
    attrs:
      long_name: band directional spread
      units: deg
      valid_min: 0.0
      valid_max: 90.0
  wave_energy_density:
    dims: [time, frequency]
    dtype: float32
    attrs:
      long_name: band energy density
      units: m^2 s
      standard_name: sea_surface_wave_variance_spectral_density
      valid_min: 0.0
  wave_a1_value:
    dims: [time, frequency]
    dtype: float32
    attrs:
      long_name: band a1 Fourier coefficient
      valid_min: -1.0
      valid_max: 1.0
      units: "1"
  wave_b1_value:
    dims: [time, frequency]
    dtype: float32
    attrs:
      long_name: band b1 Fourier coefficient
      valid_min: -1.0
      valid_max: 1.0
      units: "1"
  wave_a2_value:
    dims: [time, frequency]
    dtype: float32
    attrs:
      long_name: band a2 Fourier coefficient
      valid_min: -1.0
      valid_max: 1.0
      units: "1"
  wave_b2_value:
    dims: [time, frequency]
    dtype: float32
    attrs:
      long_name: band b2 Fourier coefficient
      valid_min: -1.0
      valid_max: 1.0
      units: "1"
  wave_check_factor:
    dims: [time, frequency]
    dtype: float32
    attrs:
      long_name: band check factor
      valid_min: 0.0
      valid_max: 2.549999952316284
      comment: Should be less than or equal to unity
      units: "1"
