attrs:
  title: waves
  description:
    Example pipeline processing data taken by a Sofar Spotter buoy deployed in Clallam
    Bay, WA
  location_id: clallam
  dataset_name: vap_waves
  data_level: b1
  fs: 2.5 # Hz
  n_bin: 1500 # 2.5 Hz * 600 s
  institution: Pacific Northwest National Laboratory

coords:
  time:
    dims: [time]
    dtype: datetime64[ms]
    attrs:
      units: Seconds since 1970-01-01 00:00:00
      long_name: Time
      standard_name: time
      timezone: UTC

data_vars:
  x:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Buoy Surge
      standard_name: platform_surge
      units: m
      valid_min: -3
      valid_max: 3
  y:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Buoy Sway
      standard_name: platform_sway
      units: m
      valid_min: -3
      valid_max: 3
  z:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Buoy Heave
      standard_name: platform_heave
      units: m
      valid_min: -3
      valid_max: 3
  lat:
    dims: [time]
    dtype: float32
    attrs:
      units: degrees_N
      long_name: Latitude
      standard_name: latitude
      valid_min: -90
      valid_max: 90
  lon:
    dims: [time]
    dtype: float32
    attrs:
      units: degrees_E
      long_name: Longitude
      standard_name: longitude
      valid_min: -180
      valid_max: 180
