classname: pipelines.vap_waves.pipeline.VapWaves
parameters:
  datastreams:
    - clallam.spotter-wave-400ms.a1
    - clallam.spotter-gps-1min.a1

triggers: []

retriever:
  path: pipelines/vap_waves/config/retriever.yaml

dataset:
  path: pipelines/vap_waves/config/dataset.yaml

quality:
  path: pipelines/vap_waves/config/quality.yaml
storage:
  path: shared/storage.yaml
