classname: pipelines.vap_waves.pipeline.VapWaves
parameters:
  datastreams:
    - cpr.spotter-pos-400ms.a1
    #- cpr.spotter-gps-1min.a1

triggers: []

retriever:
  path: pipelines/vap_waves/config/retriever.yaml

dataset:
  path: pipelines/vap_waves/config/dataset.yaml

quality:
  path: shared/quality.yaml
storage:
  path: shared/storage.yaml
