classname: tsdat.io.retrievers.StorageRetriever
parameters:
  transformation_parameters:
    # Where the point lies in the coordinate bounds (CENTER, LEFT, RIGHT)
    alignment:
      time: CENTER

    # How far to look for the next available data point
    range:
      time: 10

    # Width of the transformation (only matters for bin averaging)
    width:
      time: 1500

coords:
  time:
    name: N/A
    data_converters:
      - classname: tsdat.transform.CreateTimeGrid
        interval: 250ms

data_vars:
  x:
    .*FLT.*:
      name: x
  y:
    .*FLT.*:
      name: y
  z:
    .*FLT.*:
      name: z
  lat:
    .*LOC.*:
      name: lat
  lon:
    .*LOC.*:
      name: lon
      # data_converters:
      #   - classname: tsdat.transform.BinAverage
