classname: tsdat.io.retrievers.StorageRetriever
parameters:
  transformation_parameters:
    # Where the point lies in the coordinate bounds (CENTER, LEFT, RIGHT)
    alignment:
      time: CENTER

    # How far to look for the next available data point
    range:
      time: 10

    # Width of the transformation (only matters for bin averaging)
    width:
      time: 1

coords:
  time:
    .*wave.*:
      name: time
    # name: N/A
    # data_converters:
    #   - classname: tsdat.transform.CreateTimeGrid
    #     interval: 400ms

data_vars:
  x:
    .*wave.*:
      name: x
      # data_converters:
      #   - classname: tsdat.transform.NearestNeighbor
  y:
    .*wave.*:
      name: y
      # data_converters:
      #   - classname: tsdat.transform.NearestNeighbor
  z:
    .*wave.*:
      name: z
      # data_converters:
      #   - classname: tsdat.transform.NearestNeighbor
  lat:
    .*gps.*:
      name: lat
      # data_converters:
      #   - classname: tsdat.transform.Interpolate
  lon:
    .*gps.*:
      name: lon
      # data_converters:
      #   - classname: tsdat.transform.Interpolate
