classname: tsdat.io.retrievers.DefaultRetriever
readers:
  .*:
    classname: pipelines.adv.readers.ADVReader
    parameters:
      magnetic_declination: 14.79
      correlation_threshold: 50

coords:
  time:
    name: time
  dir:
    name: dir
  beam:
    name: beam
  inst:
    name: inst
  earth:
    name: earth

data_vars:
  velocity:
    name: vel
  flow_speed:
    name: U_mag
  flow_direction:
    name: U_dir
  amplitude:
    name: amp
  correlation:
    name: corr
  heading:
    name: heading
  pitch:
    name: pitch
  roll:
    name: roll
  # acceleration:
  #   name: accel
  # angular_velocity:
  #   name: angrt
  earth2inst_orientation:
    name: orientmat
  beam2inst_orientation:
    name: beam2inst_orientmat
  speed_of_sound:
    name: c_sound
  pressure:
    name: pressure
  temperature:
    name: temp
  error:
    name: error
  battery_voltage:
    name: batt
  orientation_down:
    name: orientation_down
