classname: pipelines.current.pipeline.Current

triggers:
  - .*\.ad2cp

retriever:
  path: pipelines/current/config/retriever.yaml

dataset:
  path: pipelines/current/config/dataset.yaml

quality:
  path: shared/quality.yaml
storage:
  path: shared/storage.yaml
